application: garfieldsearch-153603
version: 1
runtime: python27
api_version: 1
threadsafe: true
instance_class: B8
manual_scaling:
  instances: 1
# [START handlers]
handlers:

- url: /css
  static_dir: templates/css 
- url: /images
  static_dir: templates/images
- url: /js
  static_dir: templates/js  
- url: /.*
  script: main.app       



# [END handlers]

# [START libraries]
libraries:
#- name: validators
#  version: latest 
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: endpoints
  version: latest 

#- name: validators
#  version: latest   
# [END libraries]

